#!/usr/bin/env bash
# transfers a file from our client to a serve using scp
if [ $# -lt 3 ] 
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi
# valid number of arguments passed
# -i [file] : Specify the file from which to read the identity for public key authentication
# -o ssh_option : 	Set options to SSH in ssh_config format.
if [ $# -ge 4 ]
then
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
  scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
