#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt-get  update -y
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee  /var/www/html/index.html
sudo service nginx start
