#!/usr/bin/env bash
# configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > sudo /var/www/html/index.html
sed -i "37i\rewrite ^/redirect_me https://www.techtarget.com/whatis/definition/Web-server permanent;" /etc/nginx/sites-available/default
sudo service nginx start
