#!/usr/bin/env bash
# configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
# best practice to create a backup config before modification
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

#custom 404 page
echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html

CONF=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
  location /redirect_me {
    return 301 https://www.techtarget.com/whatis/definition/server;
  }
  # custom header 
  add_header X-Served-By \$hostname;

  error_page 404 /404.html;
  location = /404.html {
    internal;
  }
}"

echo -e "$CONF" | sudo tee /etc/nginx/sites-available/redirect_config

# ovoid duplicate default server block
if [ -e /etc/nginx/sites-enabled/default ]; then
  sudo rm /etc/nginx/sites-enabled/default
fi
# create link
if [ ! -e /etc/nginx/sites-enabled/redirect_config ]; then
  sudo ln -s /etc/nginx/sites-available/redirect_config /etc/nginx/sites-enabled/
fi


if [ "$(pgrep -c nginx)" -le 0 ]; then
  sudo service nginx start
else
  # sudo -S service nginx restart <<< "ubuntu"
  sudo service nginx restart
fi

