#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg_backup

# Define HAProxy configuration
CONF=\
"frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 440027-web-01 34.201.164.31:80 check
    server 440027-web-02 54.197.101.238:80 check
"

# Write configuration to a new file
echo -e "$CONF" | sudo tee /etc/haproxy/haproxy.cfg

# restart to apply changes
if [ "$(pgrep -c haproxy)" -le 0 ]; then
  sudo service haproxy restart
else
  sudo service haproxy start
fi
# HAProxy can be managed via init script
sudo systemctl enable haproxy

