-- must run in web-02 SLAVE node
CHANGE MASTER TO
  MASTER_HOST='34.201.164.31',
  MASTER_USER='replica_user',
  MASTER_PASSWORD='root',
  MASTER_LOG_FILE='mysql-bin.000090',
  MASTER_LOG_POS=154;

START SLAVE;
SHOW SLAVE STATUS\G;
