#!/usr/bin/env bash
# MySQL backup for all databases
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <root_pwd>"
    exit 1
fi
pwd="$1"
date=$(date +'%d-%m-%Y')
dump_file="backup.sql"
gz_file="${date}.tar.gz"
mysqldump -u root -p"$pwd" --all-databases > "$dump_file"
tar -czvf "$gz_file" "$dump_file"
rm "$dump_file"
