#!usr/bin/env bash
# shows listening sockets 
# shows the PID and name of the program to which each socket belongs
# option t ==> tcp
# option u ==> udp
# option l ==> listening sockets 
# option p ==> with superuser show process associated with each socket 
#sudo netstat -tulp ==> no neeed for options t and u for this task
netstat -lp 
