#!/usr/bin/env bash
# bash script run infeinitely + handle signals
file="/var/run/myscript.pid"

# update or create
sudo bash -c 'echo "$$" > $file'

# handle signals
trap 'sudo rm -f "$file"; exit' SIGQUIT
trap 'sudo rm -f "$file"; echo "I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT

while true;do
	# Displays To infinity and beyond indefinitely
	echo "To infinity and beyond"
	sleep 2
done
