#!/usr/bin/env bash
# bash script run infeinitely + handle signals
file="/var/run/myscript.pid"

cleanup() {
    echo "I hate the kill command"
    if [ -e "$file" ];then
    	rm -f $file
    fi
    exit 0
}

interrupt() {
    echo "Y U no love me?!"
}

# handle signals
trap 'cleanup' SIGTERM SIGQUIT
trap 'interrupt' SIGINT

# update or create
echo "$$" > $file

while true;do
	# Displays To infinity and beyond indefinitely
	echo "To infinity and beyond"
	sleep 2
done
