#!/usr/bin/env bash
# bash script run infeinitely + handle signals
file="/var/run/myscript.pid"

# update or create
echo "$$" > $file

# handle signals
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm "$file"' SIGQUIT SIGTERM

while true;do
	# Displays To infinity and beyond indefinitely
	echo "To infinity and beyond"
	sleep 2
done
