#!/usr/bin/env bash
# process logic

start_process() {
  (while true; do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
  done) &
  echo $! > /var/run/my_process.pid
  echo "manage_my_process started"
}

stop_process() {
  if [ -f /var/run/my_process.pid ]; then
    PID=$(cat /var/run/my_process.pid)
    kill -15 "$PID"
    # Wait for the process to stop
    wait "$PID"
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
  else
    echo "manage_my_process is not running"
  fi
}

case "$1" in
  start)
    if [ -f /var/run/my_process.pid ]; then
      echo "manage_my_process is already running. Use restart to restart it."
    else
      start_process
    fi
    ;;

  stop)
    stop_process
    ;;

  restart)
    stop_process
    start_process
    echo "manage_my_process restarted"
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

