#!/usr/bin/env bash
# process logic

case "$1" in
  start)
    if [ -f /var/run/my_process.pid ]; then
      echo "manage_my_process is already running. Use restart to restart it."
    else
      (while true; do
        echo "I am alive!" >> /tmp/my_process
        sleep 2
      done) &
      echo $! > /var/run/my_process.pid
      echo "manage_my_process started"
    fi
    ;;

  stop)
    if [ -f /var/run/my_process.pid ]; then
      PID=$(cat /var/run/my_process.pid)
      kill "$PID"
      rm /var/run/my_process.pid
      echo "manage_my_process stopped"
    else
      echo "manage_my_process is not running"
    fi
    ;;

  restart)
    if [ -f /var/run/my_process.pid ]; then
      PID=$(cat /var/run/my_process.pid)
      kill "$PID"
      rm /var/run/my_process.pid
    fi
    (while true; do
      echo "I am alive!" >> /tmp/my_process
      sleep 2
    done) &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
	
