#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd

if [ ! -e /etc/passwd ]; then
  echo "Error: /etc/passwd file not found."
  exit 1
fi

# Read the /etc/passwd file line by line
while IFS=: read -r username _ userid _ _ home _; do
  echo "Username: $username"
  echo "User ID: $userid"
  echo "Home Directory: $home"
done < /etc/passwd
