#!/usr/bin/env bash
# displays
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for item in *; do
	 if [[ "$item" != .* ]]; then
		part_to_extract="$(echo "$item" | cut -d '-' -f 2-)"
		echo "$part_to_extract"
	 fi
done
