#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
sudo sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
sudo pkill apache2
sudo service nginx restart
